config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  resources :listings do
    resources :orders, only: [:new , :create]
  end

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => 'listings#seller'

  get 'sales' => 'orders#sales'

  get 'purchases' => 'orders#purchases'
  
  resources :blogs

  root 'listings#index'
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		@blogs = Blog.all
	end

	def blog_params
		params.require(:blog).permit(:title, :body)
	end
	
	def new
		@blogs = Blog.new
	end

	def create
		@blogs = Blog.new(blog_params)

		if @blogs.save
			redirect_to blogs_path, :notice => "Your blog was created"
		else
			render "new"
		end
	end

	def edit
		@blogs = Blog.find(params[:id])
	end

	def update
		@blogs = Blog.find(params[:id])

		if @blogs.update_attributes(blog_params)
			redirect_to blogs_path, :notice => "Your post is updated"
		else
			render "edit"
		end
	end

	def show
		@blogs= Blog.find(params[:id])
	end

	def destroy

		@blogs = Blog.find(params[:id])
		@Blogs.destroy
		redirect_to blogs_path, :notice => "Your article was deleted:"

	end

	

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1> Edit Blog post </h1>
<%= form_for @blogs do |f| %>
	<p> <%= f.label :title %>: <%= f.text_field :title %> </p>
	<p> <%= f.label :body %>: <%= f.text_area :body %> </p>
	<p> <%= f.submit "Update blog Post" %> </p>
<% end %>

app/views/blogs/index.html.erb
<h1> Blog posts </h1>

<% @blogs.each do |blog| %>
	<h2><%= link_to blog.title, blog %></h2>
	<p><%= blog.body %></p>
	<% end %>

	<p><%= link_to "New Blog Post", new_blog_path %></p>

app/views/blogs/new.html.erb
<h1> new Blog post </h1>
<%= form_for @blogs do |f| %>
	<p> <%= f.label :title %>: <%= f.text_field :title %> </p>
	<p> <%= f.label :body %>: <%= f.text_area :body %> </p>
	<p> <%= f.submit "Add new blog Post" %> </p>
<% end %>

app/views/blogs/show.html.erb
<h1> <%= @blogs.title %> </h1>
<p><%= @blogs.body %></p>
<p><%= @blogs.created_at %></p>

<p>
<%= link_to "Edit", edit_blog_path(@blogs) %> ::
<%= link_to "Delete", @blogs, :confirm => "Are you Sure?", :method => :delete  %>
</p>