config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  resources :listings do
    resources :orders, only: [:new , :create]
  end

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => 'listings#seller'

  get 'sales' => 'orders#sales'

  get 'purchases' => 'orders#purchases'
  
  resources :blogs

  root 'listings#index'
  

end

app/models/listing.rb
class Listing < ActiveRecord::Base

has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100#" },
   :default_url => "http://antodoms.s3.amazonaws.com/images/default.jpg", :region => 'us-west-2',
   :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
   :path => ":style/:id_:filename"
               

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :name, :description, :price , presence: true
  
  validates :price, numericality: { greater_than:0}
  
  validates_attachment_presence :image

  belongs_to :user

  has_many :orders

  def s3_credentials
    {:bucket => 'antodoms' , :access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'], :region => 'us-west-1', :s3_host_name => 's3.amazonaws.com'}
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter  :check_user, only: [:edit, :update, :destroy]
  
  # GET /listings
  # GET /listings.json


  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    
    if current_user.recipient.blank?
         Stripe.api_key = ENV["STRIPE_API_KEY"]
         token = params[:stripeToken]
        

         recipient = Stripe::Recipient.create(
          :name => current_user.name,
          :type => "individual",
          :bank_account => token
          )
       end

    current_user.recipient = recipient.id
    current_user.save


    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])
    
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="stripe_error" class="alert alert-danger" style="display:none" >
          <noscript> Javascript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
        </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:"form-control"  %>
  </div>
 
 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:"form-control"  %>
  </div>

<br>
<% if current_user.recipient.blank? %>
<h1> Bank Account Details </h1>
   <div class="form-group">
    <%= label_tag :country %><br>
    <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class:"form-control"}  %>
  </div>

<div class="form-group">
    <%= label_tag :routing_number %><br>
    <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class:"form-control"}  %>
  </div>

  <div class="form-group">
    <%= label_tag :acount_number %><br>
    <%= text_field_tag :acount_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class:"form-control"}  %>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class:"btn btn-danger" %>
  </div>


<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class:"btn btn-link" %> |
<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1> Best in the Industry Support </h1>
  <h2> Discover one of a kind items <h2>
</div>




<div class="center">
      <div class="row">
      <% @listings.each do |listing| %>
      <div class="col-md-3">
       
       <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
           <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "sold By #{listing.user.name}" %></p>
            <% if (user_signed_in?) && (current_user == listing.user) %>
            <%= link_to 'Edit', edit_listing_path(listing) , class:"btn btn-link" %>
            <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-link" %>
            <% end %>
          </div>
        </div>
      
    </div>
     <% end %>
    </div>
</div>
<br>

<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path, class:"btn btn-link", data: { no_turbolinks: true } %>
<% end %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path , class:"btn btn-link" %>

app/views/listings/seller.html.erb
<div class="panel panel-default">
  <% if user_signed_in? %>
<div class="panel-heading">
<%= link_to 'Add a New Listing', new_listing_path, class:"btn btn-link", data: { no_turbolinks: true } %>
</div>
<% end %>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
  <tr>
    <td><%= link_to image_tag listing.image.url(:thumb) %></td>
    <td> <%= listing.name %> </td>
    <td> <%= listing.description %> </td>
    <td> <%= number_to_currency(listing.price) %> </td>
    <td> 
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "View", listing, class:"btn btn-link" %></li>
              <li><%= link_to "Edit", edit_listing_path(listing), class:"btn btn-link" %></li>
              <li><%= link_to "Delete", listing, method: :delete, data: {confirm: "Are you sure?" }, class:"btn btn-link" %></li>
            </ul>
          </div>

      
      
      
    </td>
  </tr>
  <% end %>
</table>
</div>
<br>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
  	<div class="thumbnail">
  	<%= image_tag @listing.image.url %>
  </div>
  </div>
  <div class="col-md-6">
  	<h3><%= @listing.name %></h3>
  	<h5> <%= number_to_currency(@listing.price) %></h5>
  	<p><%= @listing.description %></p>
    <br>
    <div class="center"><%= link_to "buy it now", new_listing_order_path(@listing), class:"btn btn-primary", data: { no_turbolinks: true } %></div>
  </div>
</div>

<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing) , class:"btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path , class:"btn btn-link" %>